version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: rate-limiter-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rate-limiter-app
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - IP_RATE_LIMIT=10
      - IP_BLOCK_TIME=300
      - TOKEN_RATE_LIMIT=100
      - TOKEN_BLOCK_TIME=300
      - SERVER_PORT=8080
      - TOKEN_abc123=100:60
      - TOKEN_xyz789=50:120
      - TOKEN_premium=1000:30
    restart: unless-stopped

volumes:
  redis_data: